server:
  port: 8080

spring:
  config:
    activate:
      on-profile: dev
  logging:
    level:
      org.springframework: DEBUG
  jpa.hibernate.ddl-auto: create
  jpa.properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
external:
  api:
    exchange_rate:
      uri: http://localhost:8081
      token: "dummy-token"


# Configuration for the "production" profile
---
spring:
  config:
    activate:
      on-profile: prod
  logging:
    level:
      org.springframework: INFO
  datasource:
    url: jdbc:postgresql://localhost:5432/currency_exchange
    username: postgres
    password: postgres
  jpa.hibernate.ddl-auto: create
  jpa.properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
external:
  api:
    exchange_rate:
      uri: https://v6.exchangerate-api.com/v6/
      token: ${ACCESS_TOKEN}